# This is a basic workflow to help you get started with Actions

name: data-processor.build-and-deploy

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
#       -name: Install Dependancies
#       run: todo
      
#      - name: Build
#        run: todo

#      - name: Test
#        run: todo

#      - name: Generate Test Coverage Report
#        run: todo

#      - name: Upload Artifact(s)
#        run: todo

#      -name: Make Release
#       uses: todo
#       if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: todo
#       env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Deploy Build
#        run: todo

      - name: deleteme_workflowtest
        run: echo Hello World
